name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyTest tests
        run: python -m pytest ${{ github.workspace }}/test
        env:
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          POSTS_FG_VERSION: ${{ secrets.POSTS_FG_VERSION }}
          USERS_FG_VERSION: ${{ secrets.USERS_FG_VERSION }}
          SUBREDDITS_FG_VERSION: ${{ secrets.SUBREDDITS_FG_VERSION }}
          FEATURE_VIEW_VERSION: ${{ secrets.FEATURE_VIEW_VERSION }}
      - name: Update Modal deployment
        run: modal deploy ${{ github.workspace }}/feature_pipeline.py --name feature_pipeline
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
